// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ugciirkbppcmqhxzcvcu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVnY2lpcmticHBjbXFoeHpjdmN1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU0MTMyNzEsImV4cCI6MjA3MDk4OTI3MX0.oQJn4bxy2dEjGqG50K0VlWcygmSdjTNGC6U6A8jo0I8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});